# Dependencies
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Piper's Blog
tagline:          'Day One: Test'
description:      'Teaching Piper how to Blog'
url:              http://lanyon.getpoole.com
baseurl:          '/'
paginate:         5
destination:      'gh-pages'
author:
  name:           'Piper Gray'
  url:            https://twitter.com/mdo

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/lanyon
